### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by l33tdroid** [ivanmeler/android_kernel_samsung_beyondlte#1]
Hey @ivanmeler ,

I've followed your [instruction](https://forum.xda-developers.com/galaxy-s10/samsung-galaxy-s10--s10--s10-5g-cross-device-development-exynos/rom-lineageos-17-0-s10-exynos-t4006917). it works well! 

I wanted to try and do some more customization but I wasn't able to recompile it and create a boot img. which branch should I compile? and how?

Thank You!!

**Comment by ivanmeler** [comment]
I made it easier for end user to recompile kernel with https://github.com/ivanmeler/beyond_q_kernel you can just run `source build.sh devicename` eg `source build.sh beyond2lte` and you will get boot.img on build folder, device tree will be out soon too
