### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by dexter93** [ivanmeler/android_kernel_samsung_beyondlte#3]
Kernel hangs when browsing seal pics.

Wat do?

**Comment by ivanmeler** [comment]
Make sure those were not sealion pictures, kernel panic is intended on those
![Seal-vs-SeaLion](https://user-images.githubusercontent.com/4472273/105978959-67087a80-6093-11eb-87b7-8be8b59b294a.jpg)

**Comment by ivanmeler** [comment]
> Kernel hangs when browsing seal pics.
> 
> Wat do?


Make sure those were not sealion pictures, kernel panic is intended on those
![Seal-vs-SeaLion](https://user-images.githubusercontent.com/4472273/105978959-67087a80-6093-11eb-87b7-8be8b59b294a.jpg)
